Check Docker Hub secrets

diff --git a/docker/app1-hello/node/.github/workflows/hello-node_ci.yml b/docker/app1-hello/node/.github/workflows/hello-node_ci.yml
--- a/docker/app1-hello/node/.github/workflows/hello-node_ci.yml
+++ b/docker/app1-hello/node/.github/workflows/hello-node_ci.yml
@@ -24,7 +24,7 @@ jobs:
         working-directory: docker/app1-hello/node
         run: npm install
 
-      - name: Run Tests (If any)
+      - name: Run Tests
         working-directory: docker/app1-hello/node
         run: npm test --if-present
 
@@ -39,13 +39,27 @@ jobs:
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
 
-      - name: Check Docker secrets
+      # Check whether GitHub is providing both secrets.
+      # This does NOT print the actual secret values.
+      - name: Check Docker Hub Secrets
         env:
-          USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
-          PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
+          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
+          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
         run: |
-          echo "Username length: ${#USERNAME}"
-          echo "Password length: ${#PASSWORD}"
+          echo "Docker username length: ${#DOCKER_USERNAME}"
+          echo "Docker password length: ${#DOCKER_PASSWORD}"
+
+          if [ -z "$DOCKER_USERNAME" ]; then
+            echo "ERROR: DOCKERHUB_USERNAME is empty"
+            exit 1
+          fi
+
+          if [ -z "$DOCKER_PASSWORD" ]; then
+            echo "ERROR: DOCKERHUB_PASSWORD is empty"
+            exit 1
+          fi
+
+          echo "Both Docker Hub secrets are available."
 
       - name: Login to Docker Hub
         uses: docker/login-action@v4
@@ -53,7 +67,7 @@ jobs:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_PASSWORD }}
 
-      - name: Build and push Docker Image
+      - name: Build and Push Docker Image
         uses: docker/build-push-action@v7
         with:
           context: docker/app1-hello/node
@@ -61,6 +75,3 @@ jobs:
           push: true
           tags: |
             ${{ secrets.DOCKERHUB_USERNAME }}/hello-node:latest
-
-      
-
